import Link from "next/link";
import {
  GraduationCap,
  Timer,
  Sparkles,
  BarChart3,
  Layers,
  ShieldCheck,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { getCurrentUser } from "@/lib/auth";

const appName = process.env.NEXT_PUBLIC_APP_NAME ?? "Prep Portal";

const exams = ["NEET UG", "JEE Mains", "CUET UG", "CTET", "NEET PG", "GATE"];

const features = [
  {
    icon: Timer,
    title: "Real exam simulation",
    body: "Timer-based papers with a question palette, mark-for-review and auto-submit that mirror the actual test interface.",
  },
  {
    icon: Sparkles,
    title: "AI step-by-step solutions",
    body: "Stuck on a question? Get an instant, structured explanation generated by AI right after you attempt it.",
  },
  {
    icon: Layers,
    title: "Huge question bank",
    body: "Thousands of questions organized by exam, subject, topic, tag, year and shift — previous-year papers and mocks.",
  },
  {
    icon: BarChart3,
    title: "Deep analytics",
    body: "Track accuracy, time-per-question and subject strengths across every attempt to focus your revision.",
  },
];

export default async function Home() {
  const user = await getCurrentUser();

  return (
    <div className="flex min-h-screen flex-col">
      <header className="sticky top-0 z-40 border-b border-border bg-background/80 backdrop-blur">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4">
          <Link href="/" className="flex items-center gap-2 font-semibold">
            <span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
              <GraduationCap className="size-5" />
            </span>
            {appName}
          </Link>
          <nav className="flex items-center gap-2">
            {user ? (
              <Link href="/dashboard">
                <Button>Dashboard</Button>
              </Link>
            ) : (
              <>
                <Link href="/login">
                  <Button variant="ghost">Sign in</Button>
                </Link>
                <Link href="/signup">
                  <Button>Get started</Button>
                </Link>
              </>
            )}
          </nav>
        </div>
      </header>

      <main className="flex-1">
        {/* Hero */}
        <section className="mx-auto max-w-6xl px-4 py-20 text-center sm:py-28">
          <div className="mx-auto mb-5 inline-flex items-center gap-2 rounded-full border border-border bg-muted/60 px-3 py-1 text-xs font-medium text-muted-foreground">
            <ShieldCheck className="size-3.5" />
            Built for serious aspirants
          </div>
          <h1 className="mx-auto max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl">
            Master competitive exams with{" "}
            <span className="text-primary">realistic mock tests</span> and AI
            explanations
          </h1>
          <p className="mx-auto mt-5 max-w-2xl text-lg text-muted-foreground">
            Practice previous-year papers under exam conditions, review every
            answer with AI-generated step-by-step solutions, and track exactly
            where your time and marks go.
          </p>
          <div className="mt-8 flex items-center justify-center gap-3">
            <Link href={user ? "/dashboard" : "/signup"}>
              <Button size="lg">
                {user ? "Go to dashboard" : "Start practicing free"}
              </Button>
            </Link>
            <Link href="/login">
              <Button size="lg" variant="outline">
                Sign in
              </Button>
            </Link>
          </div>

          <div className="mt-12 flex flex-wrap items-center justify-center gap-2">
            {exams.map((e) => (
              <span
                key={e}
                className="rounded-full border border-border bg-card px-3 py-1 text-sm text-muted-foreground"
              >
                {e}
              </span>
            ))}
          </div>
        </section>

        {/* Features */}
        <section className="border-t border-border bg-muted/30">
          <div className="mx-auto grid max-w-6xl gap-6 px-4 py-16 sm:grid-cols-2 lg:grid-cols-4">
            {features.map((f) => (
              <div
                key={f.title}
                className="rounded-xl border border-border bg-card p-6"
              >
                <span className="mb-4 flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
                  <f.icon className="size-5" />
                </span>
                <h3 className="font-semibold">{f.title}</h3>
                <p className="mt-2 text-sm text-muted-foreground">{f.body}</p>
              </div>
            ))}
          </div>
        </section>
      </main>

      <footer className="border-t border-border">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-2 px-4 py-8 text-sm text-muted-foreground sm:flex-row">
          <p>
            © {new Date().getFullYear()} {appName}. For learning purposes.
          </p>
          <p>NEET · JEE · CUET · CTET</p>
        </div>
      </footer>
    </div>
  );
}
